server:
  port: 8123
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
  application:
    name: ai-geek
# 邮箱服务
  mail:
    username:
    password:
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  data:
    redis:
      connect-timeout: 15
      database: 1
      host:
      timeout: 10
      port: 6379
      password:
      jedis:
        pool:
          enabled: true
          max-active: 5
          max-idle: 5
          min-idle: 0
# langchain4j
langchain4j:
  community:
    dashscope:
#      流式模型
      streaming-chat-model:
        api-key:
        model-name:
        is-multimodal-model: true
        enable-search: true
        parameters:
          enable-thinking: true
          enable-search: true
          is-multimodal-model: true
#         非流式模型
      chat-model:
        api-key:
        model-name:
        is-multimodal-model: true
        enable-search: true
        parameters:
          enable-thinking: true
          enable-search: true
          is-multimodal-model: true
#          文本向量模型，向量化模型能够将文本、图像、视频等数据转换为数学空间中的向量。通过计算向量之间的距离或夹角，可以量化数据的相似度，从而作用于精准搜索、智能推荐、自动分类及异常检测等任务。
      embedding-model:
        api-key:
        model-name:
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.qingqiu.aigeek.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn
# mcp服务
mcp:
  api-key:
  url:
# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
# sa-token
sa-token:
  token-name: authorization
  # token有效期，同一账号先后多端登录，token过期后先删除token-session，待该账号下所有token全部过期后才删除account-session。
  timeout: 7200
  is-log: true
  auto-renew: true
logging:
  level:
    dev:
      langchain4j: DEBUG

# 向量存储数据源配置
datasource:
  pg:
    host:
    port: 5432
    database:
    username:
    password:
    table:
    dimension: 1536
# searXNG联网搜索
searxng:
  url:
  timeout: 60
#  contentRetriever 配置
content-retriever:
# 最多 xxx 个检索结果
  max-Results: 6
# 过滤掉分数小于 xxx 的结果
  min-score: 0.5
# 会话记忆配置
chat-memory:
#  聊天窗口最多存储消息数量
  max-messages: 3
#  最多存储会话token数量
  max-tokens: 10000
